calliostro_spotify_web_api:

  # Your Client ID
  client_id:            'c98952c98b904658a2f4c0afa065ca4d' # Required

  # Your Client Secret
  client_secret:        'e28eb505219f4471996730afbdb793db' # Required

  # Options for SpotifyWebAPI client
  # https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/examples/setting-options.md
  options:
    auto_refresh:         false
    auto_retry:           false
    return_assoc:         false

  # Address to redirect to after authentication success OR failure
  redirect_uri:         'http://localhost:8091/spotify/callback' # Example: 'https://127.0.0.1:8000/callback/'

  # Service ID of the token provider that provides the user's access token
  token_provider:       calliostro_spotify_web_api.token_provider
